name: Add env variables

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MY_ENV: SECRET KEY

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add env variables
      run: echo "my env is $MY_ENV"
